In [3]:
from google.colab import files

uploaded = files.upload()

Saving googleplaystore_user_reviews.csv to googleplaystore_user_reviews.csv

In [4]:
import pandas as pd
df = pd.read_csv("googleplaystore_user_reviews.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  object
 1   Translated_Review       37427 non-null  object
 2   Sentiment               37432 non-null  object
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB

In [6]:
df.duplicated().sum()

np.int64(33616)

In [7]:
df.isna().sum()

App                           0
Translated_Review         26868
Sentiment                 26863
Sentiment_Polarity        26863
Sentiment_Subjectivity    26863
dtype: int64

In [8]:
df_clean=df.copy()

In [9]:
#drop na value
df_clean = df.dropna(subset=['Translated_Review']).copy()

In [14]:
#remove duplicate
df_clean = df_clean.drop_duplicates()
df_clean.duplicated().sum()

App                       0
Translated_Review         0
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

In [15]:
df_clean.isna().sum()

App                       0
Translated_Review         0
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

In [16]:
#remove spases
df_clean['App'] = df_clean['App'].str.strip()
df_clean['Translated_Review'] = df_clean['Translated_Review'].str.strip()

In [17]:
#check values between 1:-1
df_clean = df_clean[
    (df_clean['Sentiment_Polarity'] >= -1) & (df_clean['Sentiment_Polarity'] <= 1) &
    (df_clean['Sentiment_Subjectivity'] >= 0) & (df_clean['Sentiment_Subjectivity'] <= 1)
]

In [18]:
#arrange row number
df_clean.to_csv('cleaned_googleplaystore_user_reviews.csv', index=False)

In [20]:
from google.colab import files

df_clean.to_csv("googleplaystore_user_reviews.csv", index=False)
files.download("googleplaystore_user_reviews.csv")